brew "starship"
brew "yarn"

cask "visual-studio-code"
cask "iterm2"
cask "google-chrome"
cask "slack"
cask "docker"
cask "alfred"
cask "google-japanese-ime"
cask "karabiner-elements"
cask "deepl"
cask "zoom"
cask "Figma"
cask "kindle"
cask "drawio"
