add_newline = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[directory]
truncation_length = 100
truncate_to_repo = false

[memory_usage]
disabled = false
threshold = -1
symbol = " "
style = "bold dimmed blue"
